### ISSUE TITLE
Add support for PostgreSQL 12

### ISSUE THREAD

**Issue by kdubb** [impossibl/pgjdbc-ng#437]
Checklist of requirements for v12 support
- [x] Remove use of `WITH OIDS` in tests   (#436) 
- [x] Add 12 to supported versions in Gradle build files   (#436)
- [x] Add 12 to travis build matrix   (#436)
